// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqk-kW1zkdusY_yHEwvtCiSfJKDY_2RIU',
    appId: '1:772227618345:web:8eaa96ec9e24df0d1b2e38',
    messagingSenderId: '772227618345',
    projectId: 'todoapp4886',
    authDomain: 'todoapp4886.firebaseapp.com',
    storageBucket: 'todoapp4886.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWpAzwgJt4UZD7W-8TeWKULO6JYft1b4',
    appId: '1:772227618345:android:988b49c86a86986c1b2e38',
    messagingSenderId: '772227618345',
    projectId: 'todoapp4886',
    storageBucket: 'todoapp4886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYEWryZ31QELFR-TpquKEm3y2TvjgOuc',
    appId: '1:772227618345:ios:945aded7f846eec91b2e38',
    messagingSenderId: '772227618345',
    projectId: 'todoapp4886',
    storageBucket: 'todoapp4886.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYEWryZ31QELFR-TpquKEm3y2TvjgOuc',
    appId: '1:772227618345:ios:945aded7f846eec91b2e38',
    messagingSenderId: '772227618345',
    projectId: 'todoapp4886',
    storageBucket: 'todoapp4886.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqk-kW1zkdusY_yHEwvtCiSfJKDY_2RIU',
    appId: '1:772227618345:web:91be9ceab8d3df9a1b2e38',
    messagingSenderId: '772227618345',
    projectId: 'todoapp4886',
    authDomain: 'todoapp4886.firebaseapp.com',
    storageBucket: 'todoapp4886.firebasestorage.app',
  );
}
